CREATE TABLE Person
(
    person_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name   varchar(150) NOT NULL UNIQUE,
    year_of_birth int          NOT NULL
);

CREATE TABLE Book
(
    book_id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holder_id             int          REFERENCES Person (person_id) ON DELETE SET NULL,
    book_title            varchar(150) NOT NULL,
    book_author           varchar(150) NOT NULL,
    book_publication_year varchar(150) NOT NULL
);

SELECT *
FROM Person;

SELECT *
FROM Book;

INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1925);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('Brave New World', 'Aldous Huxley', 1932);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Sun Also Rises', 'Ernest Hemingway', 1926);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Grapes of Wrath', 'John Steinbeck', 1939);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('Ulysses', 'James Joyce', 1920);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('To the Lighthouse', 'Virginia Woolf', 1927);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('Lolita', 'Vladimir Nabokov', 1955);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('Nineteen Eighty-Four', 'George Orwell', 1949);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Catcher in the Rye', 'J.D. Salinger', 1951);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('Animal Farm', 'George Orwell', 1945);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('On the Road', 'Jack Kerouac', 1957);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('Under the Volcano', 'Malcolm Lowry', 1947);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('Midnight Children', 'Salman Rushdie', 1981);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Color Purple', 'Alice Walker', 1982);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Good Soldier', 'Ford Madox Ford', 1915);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Bell Jar', 'Sylvia Plath', 1963);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('One Flew Over the Cuckoo`s Nest', 'Ken Kesey', 1962);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Little Prince', 'Antoine de Saint-Exupery', 1943);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('The Name of the Rose', 'Umberto Eco', 1980);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('Waiting for Godot', 'Samuel Beckett', 1952);
INSERT INTO Book (book_title, book_author, book_publication_year)
VALUES ('All the King`s Men', 'Robert Penn Warren', 1946);

INSERT INTO Person (person_name, year_of_birth)
VALUES ('Robert De Niro', 1943);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Denzel Washington', 1954);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Katharine Hepburn', 1907);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Meryl Streep', 1949);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Clark Gable', 1901);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Bette Davis', 1908);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Gregory Peck', 1916);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Cate Blanchett', 1969);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Audrey Hepburn', 1929);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Shah Rukh Khan', 1965);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Sophia Loren', 1934);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('James Stewart', 1908);
INSERT INTO Person (person_name, year_of_birth)
VALUES ('Judy Garland', 1922);




